language: python
cache: pip
dist: xenial

matrix:
  include:
    - python: 3.7
      env: TOXENV=black
    - python: 3.7
      env: TOXENV=flake8
    - python: 2.7
      env: TOXENV=flake8

    - stage: test
      python: 2.7
      env: TOXENV=py27
    - stage: test
      python: 3.4
      env: TOXENV=py34
    - stage: test
      python: 3.5
      env: TOXENV=py35
    - stage: test
      python: 3.6
      env: TOXENV=py36
    - stage: test
      python: 3.7
      env: TOXENV=py37

install:
  - pip install tox

script:
  - tox
