language: python
python:
  - 2.7
  - 3.4
  - 3.5
  - 3.6
  - 3.7
  - 3.8
  - "nightly"
cache: pip
dist: bionic
install: 
  - pip install tox-travis codecov
script:
  - tox
after_success:
    - codecov

jobs:
  fast_finish: true
  include:
    - python: 3.7

    - python: 3.7
      env: TOXENV=flake8

    - python: 3.7
      env: TOXENV=black

    - python: 3.7
      env: TOXENV=license
